### PR TITLE
Relative paths for images + minor text tweaks

### PR DESCRIPTION
**Pull request by gherka**
Not sure if all images are required? I just copied the folder from \\freddy\dept\PHIBCS\Corp Gov\Stats Gov\User Groups\Python\Training\Images

You can see how the edited notebook looks here:
https://nbviewer.jupyter.org/github/gherka/Python-Resources/blob/master/Python%20Guidance%20for%20PHI.ipynb

### CODE REVIEW

**Comment by Tina815** [comment]
Hi German, thanks for doing it! Yeah all the images are required from that folder and I've noticed you created a folder "images"  - it will be good to embed images in this way. I will ask Calum to have a look at your pull request this week, and hopefully I can have some time next week to have a look too.

**Comment by gherka** [comment]
Nice one! I've made only a few changes (before realising that the image thing will flag up as a ton of new lines) so once we get this one through, I should be able to do more "targeted" edits that are easier to see!

**Comment by Tina815** [comment]
Hi German, I had a look at the changes. Things look good! 

In "Using this Workbook", could you change the 4 backslashes into 2 before freddy?

I noticed there is a file called "Thumbs.db" in images folder - is it something auto-generated? As after I cloned your repository, I can't see this file in images folder.

Also I noticed some keys after "press" are not changed in code chunk (thanks for doing that!). Such as:  if you are in command mode and you press C and V; Or press S while in Command Mode. Could you make sure they are all in code chunks (using \` \`)

**Comment by gherka** [comment]
Hi, that's all the changes made. As I said, this pull request is really just to make sure we can clearly see any changes without image encodings getting in the way. We can pick up other changes in later PRs.

**Comment by calumpurdie** [comment]
Thanks for doing this German. I've had a look and yeah all of those changes seem ideal. The only issue I've noticed is that the plots in the Data Visualisation section don't seem to be showing up in your link: https://nbviewer.jupyter.org/github/gherka/Python-Resources/blob/master/Python%20Guidance%20for%20PHI.ipynb

I think the data visualisation section could definitely be improved as at the moment it's quite basic, but in the meantime I think it's good to have the plots there. Do you know why they are no longer showing underneath the code? For example, the bar plot is does not show.
python plots

**Comment by gherka** [comment]
Calum, I think this is because I rerun the notebook and some data imports didn't work for me (file not found on the network). I suspect this is due to network drive mapping (I don't use H: network drive so `H:\Python Training Data` doesn't exist for me. I'll see if I can work around it.

**Review by calumpurdie — APPROVED** [review]

**Pull request merged**
